---

# https://dependabot.com/docs/config-file/

version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: "weekly"
    automerged_updates:
      - match:
          dependency_type: "all"
          update_type: "all"
