---
name: Git

permissions: {}

on:
  - pull_request

jobs:
  build:
    name: Branch is clean
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Fetch branches
        run: |
          git fetch --no-tags --prune origin "+refs/heads/${BASE}:refs/remotes/origin/${BASE}"
        env:
          BASE: ${{ github.base_ref }}
      - name: Check commits
        env:
          BASE: origin/${{ github.base_ref }}
          HEAD: HEAD
        run: |
          curl --disable --silent --show-error --location --max-time 30 "https://raw.githubusercontent.com/ViBiOh/scripts/main/bootstrap" | bash -s -- "-c" "git_branch_clean"
          scripts/git_branch_clean "${BASE}" "${HEAD}"
